export declare enum GeomCategory {
    Vector2d = "Vector2d",
    Vector3d = "Vector3d",
    Point2d = "Point2d",
    Point3d = "Point3d",
    ParamUV = "ParamUV",
    Circle = "Circle",
    Line = "Line",
    Curve = "Curve",
    CurveData = "CurveData",
    CurveId = "CurveId",
    CurvePnt = "CurvePnt",
    Surface = "Surface",
    SurfaceData = "SurfaceData",
    Plane = "Plane",
    Envelope = "Envelope",
    CurveLoop = "CurveLoop",
    CurveSegment = "CurveSegment",
    CurveSegmentId = "CurveSegmentId",
    CurveSegmentData = "CurveSegmentData",
    CurveSegmentPnt = "CurveSegmentPnt",
    LineSegment = "LineSegment",
    ArcSegment = "ArcSegment",
    NameEngine = "NameEngine"
}
